/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mail-icon-b9133b28050d43aeb973aa0f08f86441
Title: Mail Icon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


import scene from '../assets/3d/mail.glb'

const Mail = ({ currentAnimation, ...props}) => {
  const { nodes, materials } = useGLTF(scene)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials['Material.002']}
        />
      </group>
    </group>
  )
}

export default Mail;